### ISSUE TITLE
Remind date is ignored if !RemindMe is called (rather than RemindMe!)

### ISSUE THREAD

**Issue by Crashthatch** [SIlver--/remindmebot-reddit#10]
Defaults to 1 day.

See: https://www.reddit.com/r/MachineLearning/comments/5ol7od/d_who_is_using_machine_learning_and_ai_to_do_cool/dckixnh/

I have not reproduced. I read through the code but couldn't see the obvious cause.
I think the relevant code is probably here:
https://github.com/SIlver--/remindmebot-reddit/blob/master/remindmebot_search.py#L143
https://github.com/SIlver--/remindmebot-reddit/blob/master/remindmebot_search.py#L143

**Comment by SIlver--** [comment]
The issue wasn't the command. The user edited the time in after, you can see what they wrote in the "CLICK THIS LINK". They hadn't included the time until after the bot read the edit.

For example the same command, it works [here.](https://www.reddit.com/r/test/comments/5olooe/test/)
