### ISSUE TITLE
Bot is down due to a recent Reddit API change

### ISSUE THREAD

**Issue by Two-Tone** [SIlver--/remindmebot-reddit#12]
[PRAW 3.6.X no longer works due to some API changes](https://www.reddit.com/r/redditdev/comments/78f4yg/praw_version_361_no_longer_usable_after_reddit/)

[However, there is a fork of PRAW 3 that fixes these issues.](https://github.com/michael-lazar/praw3)

**Comment by SIlver--** [comment]
I have actually just fixed the issue and so it should be back up a few minutes before you made this issue. Although I did it in a different way. I didn't realize it was because of me using an older praw version(3.4). Thank you for bringing it to my attention

**Comment by SIlver--** [comment]
I have actually just fixed the issue and so it should be back up a few minutes before you made this issue. Although I did it in a different way. I didn't realize it was because of me using an older praw version(3.4). Thank you for bringing it to my attention

**Comment by Two-Tone** [comment]
Still seems to be down!
