### ISSUE TITLE
Ummm, doesn't work any more?

### ISSUE THREAD

**Issue by MagicalMonkey** [SIlver--/remindmebot-reddit#2]
I'm leaving reminders, such as this one here:

https://www.reddit.com/r/CivCraftAytos/comments/3b6fzj/make_a_wish/cskdw0i

....and they never seem to work any more, like, ever.

**Comment by SIlver--** [comment]
Yeah sorry about that. Sometimes when reddit is under heavy traffic it misses comments. The bot is basically going through the same data you are, when reddit is slow the bot will be too.

**Comment by MagicalMonkey** [comment]
How about making it so that the bot picks up itself being tagged in messages as a user like

/u/RemindMeBot +reminder etc

Then it should always receive the message?

**Comment by SIlver--** [comment]
That's a good point to add that as well. I've been hesitant to add it because most people are used to doing `RemindMe!` but including both options isn't an issue. It wasn't like this from the beginning because they only made that non-reddit gold a few months after it was made.

The only thing is that it might parse comments that are only simply talking about the bot. Example

`I really like /u/RemindMeBot`

**Comment by sagiksp** [comment]
It could look for a +reminder as a sign that it should parse it.

**Comment by SIlver--** [comment]
Using the command is no longer an issue. This was brought up as usermention being a way to not miss comments.

Before the bot would miss about probably 35% or even more calls.

Now however, the bot maybe only misses 1 out of 200? I'm not really sure it really misses comments anymore. It's hard to test with the % being so low. Even when I spammed for a while, it didn't miss one.

**Comment by jkdf2** [comment]
How were you able to get it to stop missing any comments?

**Comment by SIlver--** [comment]
I used a [3rd party API](https://github.com/SIlver--/remindmebot-reddit/blob/master/remindmebot_search.py#L437) that grabs the comments instead. It updates itself if it misses comments so if the bot goes over any comments, the API corrects that.
