### ISSUE TITLE
Remind OP

### ISSUE THREAD

**Issue by sqrtroot** [SIlver--/remindmebot-reddit#7]
Would there be interest in functions like remind op to post a reminder to the op of a comment or something?

**Comment by sqrtroot** [comment]
Tag as improvement?

**Comment by SIlver--** [comment]
Sorry, I'm not sure what OP you're referring to. To the OP of the topic or the OP of a comment?

In anyway, to understand better what you mean, if User A makes a comment, are you saying there should be a way that instead of the comment being made as a reply to User A, it's made as an independent comment for the whole thread?

**Comment by sqrtroot** [comment]
To clarify I had to scenarios in Mind. 

1:
User A makes a post
User B makes a comment ‘RemindOP! 1day "you should deliver"’
Bot comments to post next day ‘you should deliver’

2:
User A makes post
User B comments.
User C makes a comment ‘RemindOP! 1day "you should deliver"’
Bot comments to User B next day ‘you should deliver’

**Comment by SIlver--** [comment]
This can be done but shouldn't. A bot shouldn't message another user without their permission. Even though User C might have good intentions, it will always lead to it be abused. This is a Reddit wide rule for bots I'm pretty sure. Not following it will most definitely cause it to be banned.

**Comment by sqrtroot** [comment]
Hmm yeah should have thought about that :). Then I need to remind myself and send the Op a message after that. 

Thanks for the awesome work on the bot and quick replies/input :)

**Comment by SIlver--** [comment]
Thanks for your time. This did help me think of an important feature from trying to understand your point of view. So, thank you for that.
