### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by jkdf2** [SIlver--/remindmebot-reddit#8]
Would you mind creating a `requirements.txt` file with `pip freeze`, as a small convenience for someone who forks this repo? [pip freeze](https://pip.pypa.io/en/stable/reference/pip_freeze/)

Thanks 😄

**Comment by jkdf2** [comment]
As it stands, I am trying to play with the bot, but it's near impossible as many of the APIs the bot relies on are deprecated in the latest version of PRAW.

**Comment by jkdf2** [comment]
So far I have had luck with `praw-oauth2util==0.3.4` and `praw==3.4.0`.

**Comment by SIlver--** [comment]
I was actually using `praw=3.3.0`. I did not know that the new issue of `praw` was causing an issue. I'll look into it.

**Comment by jkdf2** [comment]
`praw==4.x` has completely changed almost everything the bot relies upon.
